<a href="https://colab.research.google.com/github/npxd/machine_hack/blob/master/NLP-Vignesh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NLTK Install + Imports

In [0]:
import nltk
nltk.download('popular')

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/shakespeare.zip.
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/stopwords.zip.
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/twitter_samples.zip.
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/omw.zip.
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet.zip.
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet_ic.zip.
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/words.zip.
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt.zip.
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection popular

True

In [0]:
# load tqdm
!pip install --force https://github.com/chengs/tqdm/archive/colab.zip

Collecting https://github.com/chengs/tqdm/archive/colab.zip
  Downloading https://github.com/chengs/tqdm/archive/colab.zip
     \ 634kB 3.4MB/s
Building wheels for collected packages: tqdm
  Building wheel for tqdm (setup.py) ... done
  Created wheel for tqdm: filename=tqdm-4.28.1-py2.py3-none-any.whl size=47867 sha256=e4d7edb5de455f64dfdd4199a1da370c14e5ad769b950fe7bf807aaed3a33a3f
  Stored in directory: /tmp/pip-ephem-wheel-cache-hsas9p37/wheels/41/18/ee/d5dd158441b27965855b1bbae03fa2d8a91fe645c01b419896
Successfully built tqdm
Installing collected packages: tqdm
  Found existing installation: tqdm 4.28.1
    Uninstalling tqdm-4.28.1:
      Successfully uninstalled tqdm-4.28.1
Successfully installed tqdm-4.28.1

In [0]:
from tqdm import tqdm_notebook as tqdm
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
%matplotlib inline
from keras.preprocessing.text import text_to_word_sequence, Tokenizer
from keras.preprocessing.sequence import pad_sequences
custom_style = {'axes.labelcolor': 'white',
                'xtick.color': 'white',
                'ytick.color': 'white'}
sns.set_style(rc=custom_style)
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
stopwords = set(stopwords.words('english'))
t=Tokenizer()

Using TensorFlow backend.

### Add custom stopwords here

In [0]:
for i in ',', '"', "'", ":", ";", ":", "’":  stopwords.add(i)

### Importing df

In [0]:
df = pd.read_excel("Data_Train.xlsx")
df

                                                  STORY  SECTION
0     But the most painful was the huge reversal in ...        3
1     How formidable is the opposition alliance amon...        0
2     Most Asian currencies were trading lower today...        3
3     If you want to answer any question, click on ‘...        1
4     In global markets, gold prices edged up today ...        3
5     BEIJING: Chinese tech giant Huawei has announc...        1
6     Mumbai: India Inc's external commercial borrow...        3
7     On Wednesday, Federal Reserve Chairman Jerome ...        3
8     What more can you give to the audience? I have...        2
9     com, Arbaaz Khan spoke about getting back to D...        2
10    “One would think that their development and te...        1
11    So far this year, the rupee has gained 0.7%, w...        3
12    Xiaomi, however, sees the presence of Jio in r...        1
13    The ad reads "No bells & whistles. No Bezel. N...        1
14    On Tuesday, Powell said a healthy US economy h...        3
15    This feature will help make the display more r...        1
16    TikTok, which is very popular among children, ...        1
17    The company will hive off its ratings business...        3
18    He chooses to hide his CP from colleagues, mov...        2
19    That’s right, an opera house. It simply goes t...        1
20    Facebook said eligible creators would be able ...        1
21    Starring Varun Dhawan, Alia Bhatt, Sonakshi Si...        2
22    GKN Securities which was barred over misuse of...        3
23    Fintech startup Zeta, co-founded by Bhavin Tur...        1
24    This story has been published from a wire agen...        0
25    Globally established companies such as Stratas...        1
26    The statements in which Yeddyurappa says that ...        0
27    As NDA seeks re-election, agriculture will for...        0
28    Yeddyurappa said the IAF air strikes would ben...        0
29    ”With two releases this year so far, Milan Tal...        2
...                                                 ...      ...
7598  “TDP as a party and ideology have gotten sidel...        0
7599  But so far, whenever we’ve reviewed Kindles, t...        1
7600  During the day, the markets saw high volatilit...        3
7601  Today, Gmail allows 15GB free storage. Users c...        1
7602  Aparajita Sarangi took voluntary retirement wh...        0
7603  Investors are awaiting economic growth data an...        3
7604  With advice from online survivalists, she move...        2
7605  All this time, the developers have been disgui...        1
7606  Lok Sabha elections 2019: Fifth phase of votin...        0
7607  The watchdog passed five separate orders, toge...        3
7608  In a Twitter post last week, OnePlus confirmed...        1
7609  An iOS-only email client named 'Spark' will be...        1
7610  That said, the question really is why you shou...        1
7611  And I didn’t want to do that kind of movie bec...        2
7612  His 1999 film All About My Mother received Bes...        2
7613  While Mohan Babu is not considered to be a pol...        0
7614  The S&P 500 opened higher by 1.26 points, or 0...        3
7615  However, some reports suggest that there would...        1
7616  Mumbai: Indian stocks rose, with key indices e...        3
7617  Sure, the others are slightly faster, have sli...        1
7618  With up to 14.7 million pixels, one billion co...        1
7619  A BJD supporter in Puri. Congress leaders as w...        0
7620  Bollywood celebrities took to social media to ...        2
7621  However, as of now, there is no confirmation a...        1
7622  In terms of optics, the back of the Redmi Note...        1
7623  Karnataka has been a Congress bastion, but it ...        0
7624  The film, which also features Janhvi Kapoor, w...        2
7625  The database has been created after bringing t...        1
7626  The state, which has had an uneasy relationshi...        0
7627  Virus stars Kunchacko Boban, Tovino Thomas, In...        2

[7628 rows x 2 columns]

In [0]:
target = df['SECTION'].values
df.drop(columns=['SECTION'], inplace=True)

### Data Prep

In [0]:
# tokenize and convert to lowercase. keras does it all :)
# also remove stopwords, this isnt there in keras i guess
# using sets to remove redundant words
# df['tokenized'] = [[word_tokenize(sentence) for sentence in para.split('.')] for para in tqdm(df.STORY)]
df['tokenized'] = [(list(word for word in text_to_word_sequence(para) if word not in stopwords)) for para in tqdm(df.STORY)]
df['tokenized'][0]

In [0]:
# Revert to stemmer since thats more importing (I think)
# removing the words for which the stems are the same since that eliminates the proper nouns - this is needed for embeddings with GloVe
ps = PorterStemmer()
# wnl = WordNetLemmatizer()
df['stemmed'] = [" ".join(list(ps.stem(word) for word in words if ps.stem(word) != word)) for words in tqdm(df['tokenized'])]

In [0]:
df['stemmed'][0]

'pain revers incom privat lender essenti mean ye grant fee structur deal account book borrow turn default fee tie deal crack vow account practic amort incom book gill’ way mean nasti surpris futur consid investor imag loath uncertainti promis stabl balanc come sacrific investor hope phenomen promis'

### Para 1 experiment

In [0]:
t.fit_on_texts(df.STORY.values)
max_features = 0
max_length = 0
def encode(df):
  global max_features, max_length
  encoded_docs = t.texts_to_sequences(df.STORY.values)
  matrix = t.texts_to_matrix(df.STORY.values)
  max_features = matrix.shape[1]
  max_length = 500
  return pad_sequences(encoded_docs, maxlen=max_length, padding='post')
padded_docs = encode(df)

In [0]:
print(padded_docs.shape)
print(np.unique(target))

(7628, 100)
[0 1 2 3]

### Model

In [0]:
from keras.models import Sequential
from keras.layers import Embedding, Dense, LSTM
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping

early_stopping_monitor = EarlyStopping(patience=1)
y = to_categorical(target, num_classes=4)
print(y)
model = Sequential()
model.add(Embedding(max_features, 32, input_length=max_length))
model.add(LSTM(32))
model.add(Dense(4, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

h = model.fit(padded_docs, y, epochs=10, validation_split=0.2, callbacks=[early_stopping_monitor])

W0818 10:32:23.534136 139766090938240 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0818 10:32:23.545665 139766090938240 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

[[0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 ...
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]

W0818 10:32:23.797718 139766090938240 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0818 10:32:23.823554 139766090938240 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:3295: The name tf.log is deprecated. Please use tf.math.log instead.

W0818 10:32:23.976761 139766090938240 deprecation.py:323] From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:1250: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0818 10:32:24.841765 139766090938240 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:986: The name tf.assign_add is deprecated. Please use tf.compat.v1.assign_add instead.

Train on 6102 samples, validate on 1526 samples
Epoch 1/10
6102/6102 [==============================] - 111s 18ms/step - loss: 1.3511 - acc: 0.3604 - val_loss: 1.3461 - val_acc: 0.3689
Epoch 2/10
6102/6102 [==============================] - 107s 18ms/step - loss: 1.3464 - acc: 0.3620 - val_loss: 1.3439 - val_acc: 0.3689
Epoch 3/10
 608/6102 [=>............................] - ETA: 1:32 - loss: 1.3406 - acc: 0.3569

KeyboardInterrupt: ignored

In [0]:
test_df = pd.read_excel('test.xlsx')
padded = encode(test_df)

100

In [0]:
print(len(padded[0]))

In [0]:
pred = model.predict(padded)

In [0]:
print(pred)

[[1.04244068e-01 6.55868173e-01 1.46797076e-01 9.30906460e-02]
 [6.41933759e-04 6.19958155e-02 9.36873198e-01 4.89089405e-04]
 [6.27318993e-02 7.68593371e-01 1.10681675e-01 5.79929911e-02]
 ...
 [5.85353635e-02 6.04125440e-01 2.67814249e-01 6.95249587e-02]
 [2.31047109e-01 4.77022724e-03 5.16321510e-03 7.59019494e-01]
 [8.34898204e-02 7.34388888e-01 1.13765486e-01 6.83557913e-02]]

In [0]:
pred_final = [int(np.where(prediction == prediction.max())[0][0]) for prediction in pred]
pred_final

[1,
 2,
 1,
 0,
 1,
 1,
 1,
 2,
 1,
 2,
 0,
 3,
 2,
 1,
 2,
 1,
 1,
 2,
 3,
 2,
 2,
 2,
 2,
 0,
 1,
 2,
 2,
 3,
 3,
 0,
 1,
 3,
 2,
 3,
 2,
 2,
 2,
 2,
 3,
 1,
 0,
 1,
 3,
 1,
 2,
 2,
 1,
 1,
 0,
 1,
 3,
 2,
 2,
 2,
 2,
 0,
 2,
 1,
 0,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 2,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 2,
 2,
 3,
 0,
 3,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 3,
 2,
 2,
 2,
 2,
 0,
 1,
 3,
 1,
 1,
 2,
 0,
 2,
 3,
 1,
 1,
 2,
 2,
 1,
 2,
 3,
 3,
 2,
 1,
 1,
 3,
 2,
 2,
 0,
 3,
 3,
 3,
 2,
 1,
 1,
 2,
 1,
 0,
 3,
 1,
 1,
 1,
 1,
 2,
 1,
 3,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 0,
 0,
 1,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 3,
 1,
 2,
 2,
 1,
 3,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 3,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 3,
 2,
 1,
 2,
 2,
 3,
 1,
 1,
 2,
 1,
 1,
 2,
 0,
 2,
 0,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 2,
 3,
 1,
 2,
 2,
 0,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 3,
 1,
 1,
 2,
 2,
 1,
 1,
 3,
 3,
 2,
 2,
 2,
 2,
 0,
 2,
 2,
 0,
 1,
 1,
 2,
 1,
 3,
 2,
 1,
 1,
 2,
 1,
 3,
 3,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 0,
 3,
 1,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 3,
 1,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 0,
 1,
 0,
 1,
 1,
 3,
 2,
 1,
 1,
 3,
 1,
 1,
 2,
 1,
 3,
 0,
 2,
 0,
 2,
 1,
 1,
 2,
 2,
 3,
 1,
 0,
 0,
 2,
 0,
 1,
 2,
 2,
 1,
 3,
 3,
 1,
 2,
 2,
 3,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 3,
 2,
 0,
 3,
 1,
 1,
 2,
 2,
 3,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 3,
 0,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 0,
 3,
 1,
 0,
 1,
 1,
 2,
 3,
 2,
 3,
 2,
 2,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 3,
 2,
 3,
 3,
 2,
 0,
 2,
 1,
 1,
 0,
 2,
 0,
 3,
 0,
 2,
 1,
 1,
 1,
 1,
 3,
 3,
 1,
 1,
 3,
 1,
 0,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 0,
 2,
 2,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 0,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 3,
 3,
 1,
 3,
 1,
 2,
 0,
 1,
 3,
 0,
 1,
 2,
 2,
 3,
 0,
 0,
 3,
 2,
 1,
 1,
 2,
 1,
 1,
 0,
 2,
 2,
 1,
 0,
 1,
 1,
 3,
 3,
 3,
 1,
 3,
 2,
 1,
 1,
 2,
 3,
 1,
 0,
 2,
 1,
 0,
 2,
 1,
 1,
 3,
 0,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 3,
 2,
 2,
 0,
 1,
 2,
 2,
 1,
 1,
 3,
 2,
 2,
 0,
 1,
 1,
 2,
 2,
 1,
 1,
 3,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 3,
 0,
 1,
 1,
 2,
 2,
 3,
 1,
 1,
 1,
 2,
 1,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 3,
 3,
 3,
 1,
 2,
 1,
 2,
 2,
 2,
 2,
 2,
 1,
 2,
 0,
 1,
 2,
 1,
 1,
 2,
 3,
 3,
 2,
 1,
 3,
 2,
 0,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 3,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 1,
 3,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 3,
 2,
 2,
 2,
 1,
 2,
 3,
 2,
 1,
 1,
 1,
 1,
 1,
 3,
 0,
 2,
 3,
 3,
 3,
 1,
 1,
 1,
 2,
 2,
 3,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 2,
 3,
 3,
 2,
 2,
 0,
 2,
 2,
 1,
 0,
 1,
 1,
 1,
 3,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 2,
 1,
 3,
 0,
 2,
 3,
 0,
 0,
 2,
 1,
 2,
 2,
 3,
 2,
 2,
 3,
 0,
 2,
 1,
 1,
 3,
 1,
 1,
 2,
 2,
 3,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 3,
 3,
 1,
 0,
 1,
 0,
 1,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 1,
 0,
 2,
 3,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 3,
 1,
 0,
 1,
 1,
 2,
 3,
 2,
 3,
 2,
 3,
 1,
 0,
 0,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 3,
 3,
 2,
 1,
 0,
 1,
 2,
 2,
 2,
 3,
 2,
 1,
 0,
 3,
 1,
 2,
 2,
 2,
 2,
 3,
 0,
 2,
 0,
 2,
 2,
 3,
 1,
 2,
 3,
 1,
 2,
 2,
 1,
 1,
 2,
 1,
 3,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 0,
 2,
 2,
 1,
 0,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 3,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 2,
 2,
 2,
 1,
 0,
 2,
 2,
 2,
 2,
 3,
 1,
 1,
 0,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 0,
 3,
 2,
 3,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 3,
 1,
 2,
 3,
 1,
 3,
 3,
 1,
 3,
 0,
 1,
 1,
 3,
 1,
 0,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 3,
 3,
 3,
 2,
 1,
 1,
 2,
 0,
 2,
 3,
 2,
 0,
 3,
 1,
 0,
 3,
 2,
 2,
 0,
 3,
 1,
 0,
 3,
 3,
 3,
 0,
 3,
 1,
 2,
 2,
 0,
 2,
 3,
 1,
 1,
 1,
 2,
 1,
 3,
 2,
 0,
 3,
 3,
 1,
 2,
 2,
 1,
 3,
 2,
 3,
 2,
 0,
 3,
 1,
 3,
 2,
 1,
 1,
 1,
 1,
 ...]

In [0]:
dfs = pd.read_excel('Sample_submission.xlsx')
dfs

      SECTION
0           3
1           3
2           3
3           3
4           3
5           3
6           3
7           3
8           3
9           3
10          3
11          3
12          3
13          3
14          3
15          3
16          3
17          3
18          3
19          3
20          3
21          3
22          3
23          3
24          3
25          3
26          3
27          3
28          3
29          3
...       ...
2718        2
2719        2
2720        2
2721        2
2722        2
2723        2
2724        2
2725        2
2726        2
2727        2
2728        2
2729        2
2730        2
2731        2
2732        2
2733        2
2734        2
2735        2
2736        2
2737        2
2738        2
2739        2
2740        2
2741        2
2742        2
2743        2
2744        2
2745        2
2746        2
2747        2

[2748 rows x 1 columns]

In [0]:
test_df['SECTION'] = pred_final
test_df.drop(columns=['STORY'], inplace=True)
test_df

      SECTION
0           1
1           2
2           1
3           0
4           1
5           1
6           1
7           2
8           1
9           2
10          0
11          3
12          2
13          1
14          2
15          1
16          1
17          2
18          3
19          2
20          2
21          2
22          2
23          0
24          1
25          2
26          2
27          3
28          3
29          0
...       ...
2718        0
2719        2
2720        3
2721        1
2722        0
2723        1
2724        2
2725        2
2726        2
2727        2
2728        1
2729        1
2730        3
2731        2
2732        3
2733        1
2734        0
2735        3
2736        0
2737        1
2738        1
2739        3
2740        3
2741        0
2742        0
2743        1
2744        1
2745        1
2746        3
2747        1

[2748 rows x 1 columns]

In [0]:
test_df.to_excel('Submission.xlsx')